- name: Common tools and settings
  gather_facts: true
  hosts: jitsi
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: Install system tools and utilities
    package:
      name: 
        - sudo
        - wget
        - curl
        - htop
        - nload
        - python-apt
        - apt-transport-https
        - gpg
        - gpg-agent
  - name: "Allow sudo users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      regexp: "^%sudo"
      line: "%sudo ALL=(ALL) NOPASSWD:ALL"
      validate: '/usr/sbin/visudo -cf %s'
  #requires variable for users
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "sudo,adm"
    with_items: "{{ users }}"
    when: users is defined
  #requires variable for users
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
    when: users is defined

  - name: Install Jitsi Repo signing key
    apt_key:
      url: https://download.jitsi.org/jitsi-key.gpg.key 
      state: present

  - name: Install Jitsi Repository
    apt_repository:
      repo: deb https://download.jitsi.org stable/
      state: present
      filename: jitsi-stable
      update_cache: yes
